# Generated by Django 6.0.5 on 2026-05-05 20:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0002_conversation_message_review_servicerequest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicerequest",
            name="category",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="requester",
        ),
        migrations.AlterModelOptions(
            name="conversation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="review",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveConstraint(
            model_name="listing",
            name="unique_listing_per_seller",
        ),
        migrations.AddField(
            model_name="listing",
            name="departure_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="departure_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="destination",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="origin",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="seats_available",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of available seats, spots, or tickets"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[("TRIP", "Trip"), ("TICKET", "Ticket")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="listing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="listings.listing",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="travel_listings",
                to="listings.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="contact_method",
            field=models.CharField(
                help_text="Preferred contact method, such as email, phone, or in-app message",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated cost, contribution amount, or ticket price in USD",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="seller",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="travel_listings",
                to="listings.student",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="listings.listing",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("seller", "title", "departure_date"),
                name="unique_travel_listing_per_poster",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.UniqueConstraint(
                fields=("reviewer", "reviewed_student", "listing"),
                name="unique_review_per_trip_or_ticket",
            ),
        ),
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="accepted_payment",
        ),
    ]
