# Generated by Django 5.2.8 on 2026-05-06 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_remove_servicerequest_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Harbor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="listing",
            name="category",
        ),
        migrations.CreateModel(
            name="Ship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("cargo_weight", models.FloatField()),
                ("arrival_date", models.DateField()),
                (
                    "harbor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ships",
                        to="listings.harbor",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
